AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RSI/EMA Trading Bot - Lambda + EventBridge Schedule (Secure Alpaca keys)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Architectures:
      - x86_64

Resources:
  TradingLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: lambda_function.lambda_handler

      Environment:
        Variables:
          SYMBOLS: "SPYU,TQQQ"
          RISK_PCT: "0.03"
          PAPER: "True"
          MINUTES_HISTORY: "200"
          # SSM parameter names; keys fetched inside Lambda
          ALPACA_KEY_PARAM: "/alpaca/live/key"
          ALPACA_SECRET_PARAM: "/alpaca/live/secret"

      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - arn:aws:ssm:*:*:parameter/alpaca/live/key
                - arn:aws:ssm:*:*:parameter/alpaca/live/secret

      Events:
        TradeSchedule:
          Type: Schedule
          Properties:
            Schedule: "cron(*/5 14-21 ? * MON-FRI *)"
            Name: "TradeEveryFiveMinutes"
            Description: "Runs the trading bot every 5 minutes during market hours."

Outputs:
  TradingLambdaArn:
    Description: ARN for TradingLambda
    Value: !GetAtt TradingLambda.Arn

  TradingLambdaName:
    Description: Name for TradingLambda
    Value: !Ref TradingLambda
